//------------------------------------------------------------------------------
//        This code was generated by fable-css-modules.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------

[<RequireQualifiedAccess>]
module internal CssModules

open Fable.Core

type TextAutocompleteFieldComponent =

    /// <summary>
    /// Binding for <c>dropdown-menu</c> class
    /// </summary>
    [<Emit("$0[\"dropdown-menu\"]")>]
    abstract dropdownMenu : string

